version: 0.0
os: linux
files:
  - source: /
    destination: /opt/viaweb
permissions:
  - object: /
    pattern: "**"
    owner: viaweb
    group: viaweb
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: viaweb
  ApplicationStart:
    - location: scripts/restart_server
      timeout: 300
      runas: viaweb
    